import {
  benefitIcon1,
  benefitIcon2,
  benefitIcon3,
  // benefitIcon4,
  benefitImage2,
  chromecast,
  disc02,
  figma,
  file02,
  framer,
  homeSmile,
  instagram,
  notification2,
  notification3,
  notification4,
  tensorflow,
  plusSquare,
  react,
  dart,
  nodejs,
  ai,
  python,
  aws,
  js,
  recording01,
  recording03,
  roadmap1,
  roadmap2,
  roadmap3,
  roadmap4,
  searchMd,
  flutter,
  sliders04,
  youtube,
  linkedin,
  whatsapp,
  yourlogo,
  oppologo,
  aologo,
  vishal,
  srinivas,
  vishnu,
  srivani,
  vara,
  kee,
  prava,
  rishab,
  aru,
  kavya,
  ishant,
  kapil,
  lasya,
  sneha,
  janvi,
  lokesh,
  ragha,
  varshita,
  abhi,
  pavan,
  bhavana,
  gangadhar,
  rishika,
  mani,
  kai,
} from "../assets";

export const navigation = [
  {
    id: "0",
    title: "Workshops",
    url: "#workshops",
  },
  {
    id: "1",
    title: "Benefits",
    url: "#benefits",
  },
  {
    id: "2",
    title: "Insights",
    url: "#insights",
  },
  {
    id: "3",
    title: "Roadmap",
    url: "#roadmap",
  },
  {
    id: "4",
    title: "About TEAM",
    url: "#signup",
    onlyMobile: true,
  },
  {
    id: "5",
    title: "Register Now",
    url: "#login",
    onlyMobile: true,
  },
];

export const heroIcons = [homeSmile, file02, searchMd, plusSquare];

export const notificationImages = [notification4, notification3, notification2];

export const companyLogos = [oppologo, aologo];

export const brainwaveServices = [
  "React X",
  "Python for AI",
  "Cloud Computing",
];

export const brainwaveServicesIcons = [
  recording03,
  recording01,
  disc02,
  chromecast,
  sliders04,
];

export const roadmap = [
  {
    id: "0",
    title: "Hareesh Kumar - Founder/Director at `EDTROVE EduTech`",
    text: "ReactX",
    designation: "",
    role: "Trainer",
    date: "JUNE 2024",
    status: "done",
    imageUrl: roadmap1,
    colorful: true,
  },
  // {
  //   id: "1",
  //   title: "Rahul Kumar - Ex Microsoft SDE",
  //   text: "Cloud Computing using Azure",
  //   designation: "",
  //   role:"Trainer",
  //   date: "JUNE 2024",
  //   status: "progress",
  //   imageUrl: roadmap2,
  // },
  {
    id: "1",
    title: "Pathik Ghugare - ML Engineer at `Pibit.ai`",
    text: "Hands-on PyAI",
    designation: "",
    role: "Trainer",
    date: "JUNE 2024",
    status: "done",
    imageUrl: roadmap3,
  },
  {
    id: "2",
    title: "Summit",
    text: "",
    role: "Speaker",
    date: "JUNE 2024",
    status: "progress",
    imageUrl: roadmap4,
  },
];

export const collabText =
  "With smart automation and top-notch security, it's the perfect solution for teams looking to work smarter.";

export const collabContent = [
  {
    id: "0",
    title: "Workshops & Learning Opportunities",
    // text: collabText,
  },
  {
    id: "1",
    title: "Community Engagement",
  },
  {
    id: "2",
    title: "Open to All Skill Levels",
  },
  {
    id: "3",
    title: "Certifications & Recognition",
  },
];

export const collabApps = [
  {
    id: "0",
    title: "js",
    icon: js,
    width: 26,
    height: 36,
  },
  {
    id: "1",
    title: "tensorflow",
    icon: tensorflow,
    width: 34,
    height: 36,
  },
  {
    id: "2",
    title: "nodejs",
    icon: nodejs,
    width: 36,
    height: 28,
  },
  {
    id: "3",
    title: "aws",
    icon: aws,
    width: 34,
    height: 35,
  },
  {
    id: "4",
    title: "ai",
    icon: ai,
    width: 34,
    height: 34,
  },
  {
    id: "5",
    title: "react",
    icon: react,
    width: 34,
    height: 34,
  },
  {
    id: "6",
    title: "Framer",
    icon: framer,
    width: 26,
    height: 34,
  },
  {
    id: "7",
    title: "python",
    icon: python,
    width: 38,
    height: 32,
  },
];

export const pricing = [
  {
    id: "0",
    title: "President",
    description: "AI chatbot, personalized recommendations",
    image: vishal,
    price: "0",
    features: ["Vishal"],
  },
  {
    id: "1",
    title: "Vice President",
    description: "Advanced AI chatbot, priority support, analytics dashboard",
    image: srinivas,
    price: "9.99",
    features: ["Srinivas"],
  },
  {
    id: "2",
    title: "General Secretary",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    image: vishnu,
    price: null,
    features: ["Vishnu"],
  },
  {
    id: "3",
    title: "Treasurer",
    image: srivani,
    description: "Srivani",
    price: null,
    features: ["Srivani"],
  },
  {
    id: "4",
    title: "Technical Lead",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: vara,
    features: ["Vara"],
  },
  {
    id: "5",
    title: "Design Lead",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: kee,
    features: ["Keerthna"],
  },
  {
    id: "6",
    title: "PR Manager",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: prava,
    features: ["Pravalika"],
  },
  {
    id: "7",
    title: "Documentation Head",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: rishab,
    features: ["Rishabh"],
  },
  {
    id: "8",
    title: "Curation Lead",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: aru,
    features: ["Arukiran"],
  },
  {
    id: "9",
    title: "Content Lead",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: kavya,
    features: ["Kavya"],
  },
];

export const executives = [
  {
    id: "25",
    title: "Intern",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: kai,
    features: ["Kailash"],
  },
  {
    id: "24",
    title: "Intern",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: mani,
    features: ["Maniteja"],
  },
  {
    id: "23",
    title: "Intern",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: rishika,
    features: ["Rishika"],
  },
  {
    id: "22",
    title: "Intern",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    image: gangadhar,
    price: null,
    features: ["Gangadhar"],
  },
  {
    id: "20",
    title: "Intern",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: bhavana,
    features: ["Bhavana"],
  },
  {
    id: "19",
    title: "Executive",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: pavan,
    features: ["Pavan"],
  },
  {
    id: "18",
    title: "Executive",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: abhi,
    features: ["Abhishek"],
  },
  {
    id: "17",
    title: "Executive",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: varshita,
    features: ["Varshitha"],
  },
  {
    id: "16",
    title: "Executive",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: ragha,
    features: ["Raghavendra"],
  },
  {
    id: "15",
    title: "Chief Executive",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: lokesh,
    features: ["Lokesh"],
  },
  {
    id: "14",
    title: "Chief Executive",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: janvi,
    features: ["Jahnavi"],
  },
  {
    id: "13",
    title: "Chief Executive",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: sneha,
    features: ["Sneha"],
  },
  {
    id: "12",
    title: "Chief Executive",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: lasya,
    features: ["Lasya"],
  },
  {
    id: "11",
    title: "Chief Executive",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: kapil,
    features: ["Kapil"],
  },
  {
    id: "10",
    title: "Chief Executive",
    description: "Custom AI chatbot, advanced analytics, dedicated account",
    price: null,
    image: ishant,
    features: ["Esanth"],
  },
];

export const benefits = [
  {
    id: "0",
    title: "Vishesh 2K24",
    text: "Join VISHESH, the annual tech expo! Showcase your innovative ideas and win cash prizes across all departments! ",
    date: "DATE: 27 Sep - 28 Sep",
    backgroundUrl: "./src/assets/benefits/card-1.svg",
    iconUrl: benefitIcon1,
    imageUrl: benefitImage2,
    // light: true,
  },
  {
    id: "1",
    title: "Tech Tickle",
    text: "Stay tuned for more exciting details! Coming soon—don't miss out on the updates!",
    backgroundUrl: "./src/assets/benefits/card-2.svg",
    date: "DATE: Await 🤫",
    iconUrl: benefitIcon2,
    imageUrl: benefitImage2,
    light: true,
  },
  {
    id: "2",
    title: "Ingenium 2K25.",
    text: "Stay tuned for more exciting details! Coming soon—don't miss out on the updates! ",
    backgroundUrl: "./src/assets/benefits/card-3.svg",
    date: "DATE:  Await 🤫",
    iconUrl: benefitIcon3,
    imageUrl: benefitImage2,
  },
  // {
  //   id: "3",
  //   title: "Fast responding",
  //   text: "Lets users quickly find answers to their questions without having to search through multiple sources.",
  //   backgroundUrl: "./src/assets/benefits/card-4.svg",
  //   iconUrl: benefitIcon4,
  //   imageUrl: benefitImage2,
  //   light: true,
  // },
  // {
  //   id: "4",
  //   title: "Ask anything",
  //   text: "Lets users quickly find answers to their questions without having to search through multiple sources.",
  //   backgroundUrl: "./src/assets/benefits/card-5.svg",
  //   iconUrl: benefitIcon1,
  //   imageUrl: benefitImage2,
  // },
  // {
  //   id: "5",
  //   title: "Improve everyday",
  //   text: "The app uses natural language processing to understand user queries and provide accurate and relevant responses.",
  //   backgroundUrl: "./src/assets/benefits/card-6.svg",
  //   iconUrl: benefitIcon2,
  //   imageUrl: benefitImage2,
  // },
];

export const socials = [
  {
    id: "0",
    title: "Instagram",
    iconUrl: instagram,
    url: "https://www.instagram.com/team.mrec/",
  },
  {
    id: "1",
    title: "linkedin",
    iconUrl: linkedin,
    url: "https://in.linkedin.com/company/teammrec",
  },
  {
    id: "2",
    title: "whatsapp",
    iconUrl: whatsapp,
    url: "https://chat.whatsapp.com/CG0bFlA7H8yIniZKgLtrHt",
  },
  {
    id: "3",
    title: "youtube",
    iconUrl: youtube,
    url: "https://www.youtube.com/@Team-aiml/featured",
  },
];
